version: "0.5"

processes:
  homarr:
    command: "bash -lc '${CONTAINER_COMPOSE:-docker compose} -f ${COMPOSE_FILE:-compose.yml} up --pull always --remove-orphans'"
    availability:
      restart: "on_failure"
